<template>
  <master-page
    banner-image="home.jpg"
    purple-heading-text="Disclaimer – Usage of Google Analytics"
  >
    <basic-section class="main_content_container">
      <p>This VFS Global website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer to help VFS Global analyze how visitors use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of this website, compiling reports on your website activity for pages visited, the duration and bounce rate, while providing other miscellaneous services relating to website activity and usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
      <p>You can prevent Google’s cookie generated collection of data, referring to your use of the website (incl. your IP address), plus the processing of the data, by downloading and installing the browser-plugin, which you can find here: <a
          href="https://tools.google.com/dlpage/gaoptout?hl=en"
          target="_blank"
        >https://tools.google.com/dlpage/gaoptout?hl=en</a></p>
    </basic-section>
  </master-page>
</template>

<script>
import { pageDefault } from '~/components/mixins/page';

export default {
  mixins: [pageDefault]
}
</script>